/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visuales;

import base_de_datos.GestionBD;
import dialogs.*;
import modelos.*;

/**
 *
 * @author joan
 */
public class EncuestaBuilder extends AbstractFrame{

    /**
     * Creates new form EncuestaBuilder
     */
    private Encuesta e;
    Departamento d;
    private int preguntaIndex;
    private Encuesta principal;
    private boolean flag;
    private boolean admin;

    public EncuestaBuilder(Encuesta e, Departamento d, boolean admin) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.e = e;
        this.d = d;
        this.admin = admin;
        
        preguntaIndex = 0;
        principal = null;
        flag = false;
        buttonGroup1.add(SiRadioButton);
        buttonGroup1.add(NoRadioButton);
        buttonGroup1.add(EnOcacionesRadioButton);
        inciarVicual();
        
        MessageDialog m = new MessageDialog(e.getTextoEncuesta(), "Informacion", Language.ES, this);
    }

    @Override
    public void messageDialog_returnValue(int selection) {
        
                Seleccion_de_departamento SD = new Seleccion_de_departamento(admin);
                SD.setVisible(true);
                dispose();
                
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PreguntaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PregutaEditorPane = new javax.swing.JEditorPane();
        SiRadioButton = new javax.swing.JRadioButton();
        NoRadioButton = new javax.swing.JRadioButton();
        EnOcacionesRadioButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JustificacionEditorPane = new javax.swing.JEditorPane();
        JustificacionLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numeroPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PreguntaLabel.setText("Pregunta");

        jScrollPane1.setViewportView(PregutaEditorPane);

        SiRadioButton.setText("Si");

        NoRadioButton.setText("No");

        EnOcacionesRadioButton.setText("En ocasiones");

        jScrollPane2.setViewportView(JustificacionEditorPane);

        JustificacionLabel.setText("Justificacion:");

        NextButton.setText("Siguiente");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextButtonMouseClicked(evt);
            }
        });

        BackButton.setText("Atras");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("Numero de preguntas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(187, 187, 187)
                                .addComponent(SiRadioButton)
                                .addGap(45, 45, 45)
                                .addComponent(NoRadioButton)
                                .addGap(45, 45, 45)
                                .addComponent(EnOcacionesRadioButton))
                            .addComponent(PreguntaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JustificacionLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NextButton))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(numeroPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PreguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiRadioButton)
                    .addComponent(NoRadioButton)
                    .addComponent(EnOcacionesRadioButton))
                .addGap(45, 45, 45)
                .addComponent(JustificacionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NextButton)
                    .addComponent(BackButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        if (preguntaIndex != 0 && preguntaIndex > 0) {
            preguntaIndex--;
            PregutaEditorPane.setText(e.getPreguntas().elementAt(preguntaIndex).getPregunta());

            int seleccion = e.getRespuestas().elementAt(preguntaIndex).getSeleccion();
            switch (seleccion) {
                case 0:
                    SiRadioButton.setSelected(true);
                    break;
                case 1:
                    NoRadioButton.setSelected(true);
                    break;
                default:
                    EnOcacionesRadioButton.setSelected(true);
                    break;
            }

            JustificacionEditorPane.setText(e.getRespuestas().elementAt(preguntaIndex).getArgumentacion());

            JustificacionEditorPane.setEditable(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());
            JustificacionEditorPane.setEnabled(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());

            numeroPregunta.setText((preguntaIndex + 1) + "/" + e.getPreguntas().size());
        }
        else{
            MessageDialog message = new MessageDialog("Ya no se pueden cancelar mas preguntas", "Error", AbstractFrame.Language.ES, this);
        }
    }//GEN-LAST:event_BackButtonMouseClicked

    private void NextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseClicked

        
        if (e.getPreguntas().size() > preguntaIndex) {
            
            int seleccion = -1;
            if (SiRadioButton.isSelected()) {
                seleccion = 0;
            } else if (NoRadioButton.isSelected()) {
                seleccion = 1;
            } else if (EnOcacionesRadioButton.isSelected()){
                seleccion = 2;
            }
            
            if(seleccion==-1){
                
                MessageDialog message = new MessageDialog("Debe seleccionar una de las opciones", "Error", Language.ES, this);                
                return; 
            }
            
            Respuesta R = new Respuesta(seleccion, preguntaIndex);
            e.setRespuesta(R);
            if (JustificacionEditorPane.isEditable()) {
                e.getRespuestas().elementAt(preguntaIndex).setArgumentacion(JustificacionEditorPane.getText());
            }

            PregutaEditorPane.setText(e.getPreguntas().elementAt(preguntaIndex).getPregunta());
            JustificacionEditorPane.setEditable(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());
            JustificacionEditorPane.setEnabled(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());

            buttonGroup1.clearSelection();
            JustificacionEditorPane.setText("");
            preguntaIndex++;
            numeroPregunta.setText((preguntaIndex + 1) + "/" + e.getPreguntas().size());

            if (e.getPreguntas().size() == preguntaIndex) {
            if (flag) {
                
                GestionBD.setEncuestaResuelta(principal, d);
                GestionBD.setEncuestaResuelta(e, d);
                
                MessageDialog message = new MessageDialog(1, "Se han agregado las encuestas con exito", "Informacion", Language.ES, this);
                
            } else {
                flag = true;
                principal = e;
                e = GestionBD.getEncuestaSecundaria(principal);
                preguntaIndex = 0;
                inciarVicual();
                buttonGroup1.clearSelection();
                JustificacionEditorPane.setText("");
                
                MessageDialog message = new MessageDialog(e.getTextoEncuesta(), "Informacion", Language.ES, this);
            }
        }
            
        }

    }//GEN-LAST:event_NextButtonMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Seleccion_de_departamento SD = new Seleccion_de_departamento(admin);
        SD.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton EnOcacionesRadioButton;
    private javax.swing.JEditorPane JustificacionEditorPane;
    private javax.swing.JLabel JustificacionLabel;
    private javax.swing.JButton NextButton;
    private javax.swing.JRadioButton NoRadioButton;
    private javax.swing.JLabel PreguntaLabel;
    private javax.swing.JEditorPane PregutaEditorPane;
    private javax.swing.JRadioButton SiRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numeroPregunta;
    // End of variables declaration//GEN-END:variables

    private void inciarVicual() {
        PregutaEditorPane.setText(e.getPreguntas().elementAt(preguntaIndex).getPregunta());
        PregutaEditorPane.setEditable(false);
        JustificacionEditorPane.setEditable(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());
        JustificacionEditorPane.setEnabled(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());

        numeroPregunta.setText((preguntaIndex + 1) + "/" + e.getPreguntas().size());
        PreguntaLabel.setText(e.getObjEncuesta());
    }
}
