/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visuales;

import base_de_datos.GestionBD;
import dialogs.*;
import modelos.*;

/**
 *
 * @author joan
 */
public class EncuestaBuilder extends javax.swing.JFrame{

    /**
     * Creates new form EncuestaBuilder
     */
    private Encuesta e;
    Departamento d;
    private int preguntaIndex;
    private Encuesta principal;
    private boolean flag;

    public EncuestaBuilder(Encuesta e, Departamento d) {
        initComponents();
        this.e = e;
        this.d = d;
        preguntaIndex = 0;
        principal = null;
        flag = false;
        buttonGroup1.add(SiRadioButton);
        buttonGroup1.add(NoRadioButton);
        buttonGroup1.add(EnOcacionesRadioButton);
        inciarVicual();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PreguntaLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PregutaEditorPane = new javax.swing.JEditorPane();
        SiRadioButton = new javax.swing.JRadioButton();
        NoRadioButton = new javax.swing.JRadioButton();
        EnOcacionesRadioButton = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JustificacionEditorPane = new javax.swing.JEditorPane();
        JustificacionLabel = new javax.swing.JLabel();
        NextButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        numeroPregunta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PreguntaLabel.setText("Pregunta");

        jScrollPane1.setViewportView(PregutaEditorPane);

        SiRadioButton.setText("Si");

        NoRadioButton.setText("no");

        EnOcacionesRadioButton.setText("En ocaciones");

        jScrollPane2.setViewportView(JustificacionEditorPane);

        JustificacionLabel.setText("Justificacion");

        NextButton.setText("Siguiente");
        NextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NextButtonMouseClicked(evt);
            }
        });

        BackButton.setText("Atras");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });

        jLabel1.setText("#preguntas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JustificacionLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(PreguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(numeroPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1)
                            .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(SiRadioButton)
                            .addGap(169, 169, 169)
                            .addComponent(NoRadioButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                            .addComponent(EnOcacionesRadioButton)
                            .addGap(100, 100, 100)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NextButton)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(PreguntaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(numeroPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SiRadioButton)
                    .addComponent(NoRadioButton)
                    .addComponent(EnOcacionesRadioButton))
                .addGap(33, 33, 33)
                .addComponent(JustificacionLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton)
                    .addComponent(BackButton))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        if (preguntaIndex != 0 && preguntaIndex > 0) {
            preguntaIndex--;
            PregutaEditorPane.setText(e.getPreguntas().elementAt(preguntaIndex).getPregunta());

            int seleccion = e.getRespuestas().elementAt(preguntaIndex).getSeleccion();
            switch (seleccion) {
                case 0:
                    SiRadioButton.setSelected(true);
                    break;
                case 1:
                    NoRadioButton.setSelected(true);
                    break;
                default:
                    EnOcacionesRadioButton.setSelected(true);
                    break;
            }

            JustificacionEditorPane.setText(e.getRespuestas().elementAt(preguntaIndex).getArgumentacion());

            JustificacionEditorPane.setEditable(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());

            numeroPregunta.setText((preguntaIndex + 1) + "/" + e.getPreguntas().size());
        }
    }//GEN-LAST:event_BackButtonMouseClicked

    private void NextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NextButtonMouseClicked

        
        if (e.getPreguntas().size() > preguntaIndex) {
            
            int seleccion = -1;
            if (SiRadioButton.isSelected()) {
                seleccion = 0;
            } else if (NoRadioButton.isSelected()) {
                seleccion = 1;
            } else if (EnOcacionesRadioButton.isSelected()){
                seleccion = 2;
            }
            
            if(seleccion==-1){
                return; 
            }
            
            Respuesta R = new Respuesta(seleccion, preguntaIndex);
            e.setRespuesta(R);
            if (JustificacionEditorPane.isEditable()) {
                e.getRespuestas().elementAt(preguntaIndex).setArgumentacion(JustificacionEditorPane.getText());
            }

            PregutaEditorPane.setText(e.getPreguntas().elementAt(preguntaIndex).getPregunta());
            JustificacionEditorPane.setEditable(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());

            buttonGroup1.clearSelection();
            JustificacionEditorPane.setText("");
            preguntaIndex++;
            numeroPregunta.setText((preguntaIndex + 1) + "/" + e.getPreguntas().size());

            if (e.getPreguntas().size() == preguntaIndex) {
            if (flag) {
                
                GestionBD.setEncuestaResuelta(principal, d);
                GestionBD.setEncuestaResuelta(e, d);
                
                Seleccion_de_departamento SD = new Seleccion_de_departamento();
                SD.setVisible(true);
                dispose();
            } else {
                flag = true;
                principal = e;
                e = GestionBD.getEncuestaSecundaria(principal);
                preguntaIndex = 0;
                inciarVicual();
                buttonGroup1.clearSelection();
                JustificacionEditorPane.setText("");
            }
        }
            
        }

    }//GEN-LAST:event_NextButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JRadioButton EnOcacionesRadioButton;
    private javax.swing.JEditorPane JustificacionEditorPane;
    private javax.swing.JLabel JustificacionLabel;
    private javax.swing.JButton NextButton;
    private javax.swing.JRadioButton NoRadioButton;
    private javax.swing.JLabel PreguntaLabel;
    private javax.swing.JEditorPane PregutaEditorPane;
    private javax.swing.JRadioButton SiRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numeroPregunta;
    // End of variables declaration//GEN-END:variables

    private void inciarVicual() {
        PregutaEditorPane.setText(e.getPreguntas().elementAt(preguntaIndex).getPregunta());
        PregutaEditorPane.setEditable(false);
        JustificacionEditorPane.setEditable(e.getPreguntas().elementAt(preguntaIndex).isArgumentacion());

        numeroPregunta.setText((preguntaIndex + 1) + "/" + e.getPreguntas().size());
        PreguntaLabel.setText(e.getObjEncuesta());
    }
}
