/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visuales;

import base_de_datos.GestionBD;
import java.awt.Font;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author electro-zombie
 */
public class Estadisticas extends javax.swing.JFrame {

    /**
     * Creates new form Estadisticas
     */
    public Estadisticas() {
        initComponents();
   
        Vector<int[]> estadisticas = GestionBD.getEstadisticasDepartamento(Integer.parseInt(annos.getSelectedItem()+""));        
        actualizarTablaEstadisticas(estadisticas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstadisticas = new javax.swing.JTable();
        salirBoton = new javax.swing.JButton();
        actualizarTotal = new javax.swing.JButton();
        mostrarDatos = new javax.swing.JButton();
        annos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaEstadisticas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEstadisticas);

        salirBoton.setText("jButton1");

        actualizarTotal.setText("jButton1");

        mostrarDatos.setText("jButton2");

        annos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(15, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actualizarTotal)
                        .addGap(18, 18, 18)
                        .addComponent(mostrarDatos)
                        .addGap(18, 18, 18)
                        .addComponent(annos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salirBoton)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizarTotal)
                    .addComponent(mostrarDatos)
                    .addComponent(salirBoton)
                    .addComponent(annos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizarTotal;
    private javax.swing.JComboBox<String> annos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrarDatos;
    private javax.swing.JButton salirBoton;
    private javax.swing.JTable tablaEstadisticas;
    // End of variables declaration//GEN-END:variables

 private void actualizarTablaEstadisticas(Vector<int[]> est) {
        
        DefaultTableModel d = new DefaultTableModel() {
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        ;
        };
        Object[] OBJ = new Object[10];
        d.addColumn("Departamento");
        d.addColumn("Si");
        d.addColumn("<- Porciento");
        d.addColumn("No");
        d.addColumn("<- Porciento");
        d.addColumn("En ocasiones");
        d.addColumn("<- Porciento");
        d.addColumn("Total de encuestados");
        d.addColumn("Numero de encuestados");
        d.addColumn("<- Porciento");
        
        for (int i = 0; i < est.size(); i++) {
            
            OBJ[0] = GestionBD.getDepartamento(i+1).getNombreDepartamento();
            OBJ[1] = est.elementAt(i)[0];
            OBJ[3] = est.elementAt(i)[1];
            OBJ[5] = est.elementAt(i)[2];
            OBJ[2] = (Double)OBJ[1]*100/((Double)OBJ[1]+(Double)OBJ[3] + (Double)OBJ[5]);
            OBJ[4] = (Double)OBJ[3]*100/((Double)OBJ[1]+(Double)OBJ[3] + (Double)OBJ[5]);
            OBJ[6] = (Double)OBJ[5]*100/((Double)OBJ[1]+(Double)OBJ[3] + (Double)OBJ[5]);
            OBJ[7] = est.elementAt(i)[3];
            OBJ[8] = est.elementAt(i)[4];
            OBJ[9] = (Double)OBJ[8]*100/((Double)OBJ[7]);
            
            d.addRow(OBJ);
        }
        
        tablaEstadisticas = new JTable(d);
        
        tablaEstadisticas.setFont(new Font("arial", Font.BOLD, 14));
        tablaEstadisticas.setRowHeight(30);
        tablaEstadisticas.setShowGrid(true);
        
        jScrollPane1.setViewportView(tablaEstadisticas);
        
    }
}
