/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visuales;

import base_de_datos.GestionBD;
import dialogs.AbstractFrame;
import dialogs.MessageDialog;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import utiles.CheckBoxEditor;
import utiles.ComponentRenderer;
import utiles.Tupla;

/**
 *
 * @author electro-zombie
 */
public class EstadisticasDepartamento extends AbstractFrame {

    /**
     * Creates new form EstadisticasDepartamento
     */
    
    private final String nombreDepartamento;
    private final int anno;
    private Tupla<Tupla<Integer, Integer>,Tupla<Object[], Object[]>> datosPregunta;
    
    public EstadisticasDepartamento(String nombreDepartamento, int anno) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.nombreDepartamento = nombreDepartamento;
        this.anno = anno;
        
        datosPregunta = GestionBD.getEstadisticasDepartamento(nombreDepartamento, anno);
        
        CantTrabLabel.setText(datosPregunta.getElemento1().getElemento1()+"");
        cantEncLabel.setText(datosPregunta.getElemento1().getElemento2()+"");
        departamento.setText(nombreDepartamento);
        
        actualizarTablaPreguntas(datosPregunta.getElemento2());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CantidadTrabajadores = new javax.swing.JLabel();
        CantTrabLabel = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        cantidadEncuestas = new javax.swing.JLabel();
        cantEncLabel = new javax.swing.JLabel();
        Reporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPreguntas = new javax.swing.JTable();
        departamento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CantidadTrabajadores.setText("Cantidad de Trabajadores");

        Atras.setText("Atras");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        cantidadEncuestas.setText("Cantidad de Encuestados");

        Reporte.setText("Reporte");
        Reporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReporteMouseClicked(evt);
            }
        });

        tablaPreguntas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaPreguntas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Atras)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CantidadTrabajadores)
                                .addGap(18, 18, 18)
                                .addComponent(CantTrabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Reporte))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cantidadEncuestas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cantEncLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 259, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(departamento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CantidadTrabajadores)
                                .addComponent(cantidadEncuestas))
                            .addComponent(cantEncLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Reporte)
                            .addComponent(Atras)))
                    .addComponent(CantTrabLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteMouseClicked
        ReporteBuilder RB = new ReporteBuilder(GestionBD.getDepartamento(nombreDepartamento), datosPregunta);
        RB.setVisible(true);
        dispose();
    }//GEN-LAST:event_ReporteMouseClicked

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        Estadisticas E = new Estadisticas();
        E.setVisible(true);
        dispose();
    }//GEN-LAST:event_AtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel CantTrabLabel;
    private javax.swing.JLabel CantidadTrabajadores;
    private javax.swing.JButton Reporte;
    private javax.swing.JLabel cantEncLabel;
    private javax.swing.JLabel cantidadEncuestas;
    private javax.swing.JLabel departamento;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPreguntas;
    // End of variables declaration//GEN-END:variables

    private void actualizarTablaPreguntas(Tupla<Object[], Object[]> T) {

         DefaultTableModel d = new DefaultTableModel() {
            
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 7;
            }
        ;
        };
        Object[] OBJ = new Object[8];
        d.addColumn("Indice de pregunta");
        d.addColumn("Si");
        d.addColumn("<- Porciento");
        d.addColumn("No");
        d.addColumn("<- Porciento");
        d.addColumn("En ocasiones");
        d.addColumn("<- Porciento");
        d.addColumn("Justificaciones");
        
        for (int i = 0; i < T.getElemento1().length; i++) {
            Tupla temp = (Tupla<Integer[], Vector<String>>)T.getElemento1()[i];
            Integer[] I = (Integer[])temp.getElemento1();

            double totalP = I[0]+I[1]+I[2];
            OBJ[0] = (i+1);
            OBJ[1] = I[0];
            OBJ[2] = (Double)(I[0]*100.0)/totalP;
            OBJ[3] = I[1];
            OBJ[4] = (Double)(I[1]*100.0)/totalP;
            OBJ[5] = I[2];
            OBJ[6] = (Double)(I[2]*100.0)/totalP;
            OBJ[7] = new JCheckBox();
            
            d.addRow(OBJ);
        }
        JCheckBox check = new JCheckBox();
        check.setEnabled(false);
        Object[] O = {"Encuesta secundaria", "", "", "", "", "", "", check};
        d.addRow(O);
        
        for (int i = 0; i < T.getElemento2().length; i++) {
            Tupla temp = (Tupla<Integer[], Vector<String>>)T.getElemento2()[i];
            Integer[] I = (Integer[])temp.getElemento1();

            double totalP = I[0]+I[1]+I[2];
            OBJ[0] = (i+1);
            OBJ[1] = I[0];
            OBJ[2] = (Double)(I[0]*100.0)/totalP;
            OBJ[3] = I[1];
            OBJ[4] = (Double)(I[1]*100.0)/totalP;
            OBJ[5] = I[2];
            OBJ[6] = (Double)(I[2]*100.0)/totalP;
            JCheckBox JC = new JCheckBox();
            OBJ[7] = JC;
            
            d.addRow(OBJ);
        }
        
        tablaPreguntas = new JTable(d);
        
        tablaPreguntas.setFont(new Font("arial", Font.BOLD, 14));
        tablaPreguntas.setRowHeight(30);
        tablaPreguntas.setShowGrid(true);
        
        
        tablaPreguntas.getColumn("Justificaciones").setCellRenderer(
                new ComponentRenderer());
        tablaPreguntas.getColumn("Justificaciones").setCellEditor(
                new CheckBoxEditor(new JCheckBox()));
        
        tablaPreguntas.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                int fila = tablaPreguntas.rowAtPoint(e.getPoint());
                int columna = tablaPreguntas.columnAtPoint(e.getPoint());
                
                if (fila > -1 && columna == 7) {
                
                    String just = "";
                    Tupla temp = (Tupla<Integer[], Vector<String>>)T.getElemento1()[fila];
                    Vector<String> V = (Vector<String>)temp.getElemento2();
                    
                    for(int i = 0; i < V.size(); i++){
                        just += (i+1) + ": " + V.elementAt(i) + "\n";
                    }
                    
                    MessageDialog message = new MessageDialog(just, "Distintas opiniones", AbstractFrame.Language.ES, EstadisticasDepartamento.this);
                    
                    
                }
                    
                
            }
            
        });
        
        jScrollPane1.setViewportView(tablaPreguntas);
        
    }

}
