/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visuales;

import com.itextpdf.text.DocumentException;
import dialogs.AbstractFrame;
import dialogs.InputDialog;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileNotFoundException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelos.Departamento;
import modelos.Encuesta;
import utiles.CheckBoxEditor;
import utiles.ComponentRenderer;
import utiles.Tupla;
import utiles.reporte;

/**
 *
 * @author joan
 */
public class ReporteBuilder extends AbstractFrame {

    /**
     * Creates new form ReporteBuilder
     */
    private final Vector<JCheckBox> check;
    private final Departamento departamento;
    private final Tupla<Tupla<Integer, Integer>, Tupla<Object[], Object[]>> informacionEncuestas;
    private final Vector<String> justificacionesT = new Vector<>();
    private String conclusiones;
    private final Vector<String> justificacionesRales = new Vector<>();
    private final int anno;
    private String justificacionRemp = "";

    public ReporteBuilder(Departamento depratamento, Tupla<Tupla<Integer, Integer>, Tupla<Object[], Object[]>> informacionEncuestas, int anno) {
        initComponents();
        check = new Vector<>();
        this.departamento = depratamento;
        this.informacionEncuestas = informacionEncuestas;
        this.anno = anno;

        llenarJustificaciones();
        this.setLocationRelativeTo(null);

        Actualizar_tabla();
        conclusiones = jEditorPane1.getText();
        departamentoTextoLabel.setText(depratamento.getNombreDepartamento());
        conclusiones = "";
    }

    @Override
    public void inputDialog_returnValue(Object returnValue, int selection) {
        if (selection == 1) {
            if (returnValue != null) {

                conclusiones = (String) returnValue;

            }
        } else if (selection == 2) {
            justificacionesT.add((String) returnValue);
                Actualizar_tabla();
        } else if (selection == 3) {
              //corregir tambien en la base de datos
                String temp = (String) returnValue;
                justificacionesT.insertElementAt(temp, justificacionesT.indexOf(justificacionRemp));
                Actualizar_tabla();
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchencked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Conclusion = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        ConclusionLabel = new javax.swing.JLabel();
        ConlcusionButton = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        justificaciones = new javax.swing.JTable();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        departamentoLabel = new javax.swing.JLabel();
        departamentoTextoLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JustificacionExtraButton = new javax.swing.JButton();

        jScrollPane2.setViewportView(jEditorPane1);

        ConclusionLabel.setText("Conclusion");

        ConlcusionButton.setText("Aceptar");
        ConlcusionButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConlcusionButtonMouseClicked(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ConclusionLayout = new javax.swing.GroupLayout(Conclusion.getContentPane());
        Conclusion.getContentPane().setLayout(ConclusionLayout);
        ConclusionLayout.setHorizontalGroup(
            ConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConclusionLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(ConclusionLabel)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConclusionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConclusionLayout.createSequentialGroup()
                        .addComponent(ConlcusionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cancelar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE))
                .addContainerGap())
        );
        ConclusionLayout.setVerticalGroup(
            ConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConclusionLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(ConclusionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(ConclusionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConlcusionButton)
                    .addComponent(Cancelar))
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        justificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(justificaciones);

        aceptar.setText("Aceptar");
        aceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aceptarMouseClicked(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelarMouseClicked(evt);
            }
        });

        departamentoLabel.setText("Departamento");

        jButton1.setText("Agregar conclusiones");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        JustificacionExtraButton.setText("Agregar Justificacion extra");
        JustificacionExtraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JustificacionExtraButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(aceptar)
                        .addGap(27, 27, 27)
                        .addComponent(JustificacionExtraButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(departamentoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(departamentoTextoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentoLabel)
                    .addComponent(departamentoTextoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar)
                    .addComponent(cancelar)
                    .addComponent(jButton1)
                    .addComponent(JustificacionExtraButton))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        InputDialog input = new InputDialog(1, "Escriba las conclusiones", "Conclusiones", conclusiones, AbstractFrame.Language.ES, this);
    }//GEN-LAST:event_jButton1MouseClicked

    private void ConlcusionButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConlcusionButtonMouseClicked
        conclusiones = jEditorPane1.getText();
        Conclusion.setVisible(false);
    }//GEN-LAST:event_ConlcusionButtonMouseClicked

    private void CancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelarMouseClicked
        Conclusion.setVisible(false);
    }//GEN-LAST:event_CancelarMouseClicked

    private void aceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aceptarMouseClicked
        try {
            llenarJustificacionesReales();
            reporte.reporteBuild(departamento, true, anno, informacionEncuestas, Encuesta.getAllpreguntas(), justificacionesRales, conclusiones);
            lectorDePDF lp = new lectorDePDF(System.getProperty("user.dir") + System.getProperty("file.separator") + /*departamento.getNombreDepartamento()*/"X" + " - " + anno + ".pdf");
            lp.setVisible(true);
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(ReporteBuilder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_aceptarMouseClicked

    private void cancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelarMouseClicked
        EstadisticasDepartamento es = new EstadisticasDepartamento(departamento.getNombreDepartamento(), anno);
        es.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelarMouseClicked

    private void JustificacionExtraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JustificacionExtraButtonMouseClicked
        InputDialog input = new InputDialog(2, "Escriba las conclusiones", "Conclusiones", conclusiones, AbstractFrame.Language.ES, this);
    }//GEN-LAST:event_JustificacionExtraButtonMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JDialog Conclusion;
    private javax.swing.JLabel ConclusionLabel;
    private javax.swing.JButton ConlcusionButton;
    private javax.swing.JButton JustificacionExtraButton;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel departamentoLabel;
    private javax.swing.JLabel departamentoTextoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable justificaciones;
    // End of variables declaration//GEN-END:variables
    private void Actualizar_tabla() {
        check.clear();
        DefaultTableModel d = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 1;
            }
        };

        Object[] OBJ = new Object[2];
        d.addColumn("Justificaciones");
        d.addColumn("Seleccion");
        for (String justificacionesT1 : justificacionesT) {
            OBJ[0] = justificacionesT1;
            check.add(new JCheckBox("", false));
            OBJ[1] = check.lastElement();
            d.addRow(OBJ);
        }

        justificaciones = new JTable(d);

        justificaciones.setFont(new Font("arial", Font.BOLD, 14));
        justificaciones.setRowHeight(30);
        justificaciones.setShowGrid(true);

        justificaciones.getColumn("Seleccion").setCellRenderer(
                new ComponentRenderer());
        justificaciones.getColumn("Seleccion").setCellEditor(
                new CheckBoxEditor(new JCheckBox()));
        justificaciones.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {

                int fila = justificaciones.rowAtPoint(e.getPoint());
                int columna = justificaciones.columnAtPoint(e.getPoint());

                if (fila > -1 && columna == 0) {
                    justificacionRemp = justificacionesT.elementAt(fila);
                    InputDialog input = new InputDialog(3, "Justificaciones", "Justificaiones", justificacionesT.elementAt(fila), AbstractFrame.Language.ES, ReporteBuilder.this);

                }

            }

        });
        jScrollPane1.setViewportView(justificaciones);

    }

    private void llenarJustificaciones() {
        for (int i = 0; i < informacionEncuestas.getElemento2().getElemento1().length; i++) {
            Tupla<Integer[], Vector<String>> T = (Tupla<Integer[], Vector<String>>) informacionEncuestas.getElemento2().getElemento1()[i];
            for (int j = 0; j < T.getElemento2().size(); j++) {
                justificacionesT.add(T.getElemento2().elementAt(j));
            }
        }
    }

    private void llenarJustificacionesReales() {
        for (int i = 0; i < justificacionesT.size(); i++) {
            if (check.elementAt(i).isSelected()) {
                justificacionesRales.add(justificacionesT.elementAt(i));
            }
        }
    }

}
